language: ruby
os:
- linux
dist: xenial
services:
- docker
env:
  global:
  - TAG="${TRAVIS_TAG#*-}"
  - IMAGE="${TRAVIS_TAG%%-*}"
  - IMAGE_NAME="${IMAGE#*_}"
  - IMAGE_TAG="${IMAGE%%_*}"
  - secure: bGsN30kn707De+YgCz68Nsiv+Iu/nOTkuX84I/G8x4uTW+RB8YKDdxgY+XbmjbQjO8b8mu4lQvUIw7MpofSVa68kOWmpglw1wmKiJ9MKSG49jZxI88RkmOXdi5EyGeiIuuRxgtPI4O4Kfs+pqAPPyVL/IerD4KGd6n+AjD31cyrqvjOdaNybFIruQ+5/de54AmLRGCJs/JkkA+dVdNBXQY2IGwZ9JySdlbTykNEI5FZ/TnoACBt7aPiT6ZipuWawJzScoHq3L1mEWy9ig5YXq5I4A1y9qU3IiFU40uGfLZrr12yFvOHH7Sdu/g3oiVtwoa1qibTL+5w3w0pPahkhpW/c9L65Vq78GdtvUzPgpzjNe3rlYHI/rw7oMwKCO1wnRMDvMW4sIF5gTX1lIF47dFy+cHyjtyvQrkDHgmIJfRletwFnOaQK29wT9jT0YH25d5yiJJMQZX6dGTbkjM07lbIUL9k0XywzYZd6TVovpR5ghRR//j94WQI7SbKUaUzmWX7hw6eSfqDNVm0GWnwzoCS3KV1L36HhUniJmoAEyM0XpHkuwymxPBBcZPY0AxT5d6rfmLvI0uQBm61n/z8d5sgOaKU89e4TEmfh71DBLJ3gVDCYpU/XvyCBaFkhTryQnZmi9uh+sdukgPBVCVjTeAkmQ5o9D388LaH1FpU9CJA=
  - secure: VcilkcH/tKvyCZcrt0dTlHtrrZwTfBOJRAVu5Hl3IwKJvYEuoImDPy97QpTq+1mMK4ydEHP3gJszAwTUKUgFYBtYWa7FEeai2PJ7OF/2VCipdrHhShNrjQjYt0c0RHjk28PVVlF55TudSV1ksh+fAVHSPO8dXt9WQ/1Gpe/g/XeY2lFukih1n2OWjvMDObFgmxX5l3LlLZ5OP8LEPDBnvaawwVz54ubJxE5QawInHaQVUgRQmyriQGvo7rHY8L3RO88cW27I98rT8VVvTedoNHrzTVleHWq+4I+lri17rlYhfPMBJ3BjqjWUp4mHr2w1d38NzKqyNJ+q2KJ7GBbeC2KMSMjqgg/gHC9oxgoailRQvjz/JqkT12pTsYIAlHtUX8y232OxviNiuchkPp+RcGx+/ZXMVBtF2Y87FYaiz6DZ+vHTrkY/0GD5KEohSkVvDMozbmnBLpy720miQAa194qU/4vHOr8D8P3jQqnggiTEnbWzbs3I7RvTyZJvgT6gikFf8JCuNCzwOYV6k56+OjPdbv6IelxSkhvM/y1sfDWH0aQRw2Fg+qoG1l2NmZzHbw9MLiFtApT0T09APpi4QqsR4Mux83Z91XGu7f5+rJTJsEyIEUM3VZjMybyIaK/GgGWMDfFVjhKtW/zxIzwF4KHyVO/SwyAUlCBMn0qHP1U=

jobs:
  include:
  - stage: build
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t "$IMAGE_TAG" "$IMAGE_NAME"
    - docker images
  - stage: deploy
    script:
    - docker tag "$IMAGE_TAG" "$DOCKER_USERNAME/$IMAGE_TAG"
    - docker push "$DOCKER_USERNAME/$IMAGE_TAG"
stages:
- name: build
  if: tag IS present
- name: deploy
  if: tag IS present
