# armhf service meant to run kuzzle on a 32bit Raspberry Pi
version: '1'

services:
  kuzzle:
    image: chokapeek/kuzzle-armhf:2.2.2
    ports:
      - "7512:7512"
      - "1883:1883"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - NODE_ENV=production

  redis:
    image: redis:5

  elasticsearch:
    image: chokapeek/es-kuzzle-armhf:7.4.2
    ulimits:
      nofile: 65536
